vich_uploader:
    db_driver: orm

    mappings:
      category_image:
        uri_prefix: /img/categories
        upload_destination: '%kernel.project_dir%/public/img/categories'

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
